# Windows (MSVC): link the C runtime statically everywhere.
# sherpa-onnx's prebuilt Windows static libs are built with /MT
# (RuntimeLibrary MT_StaticRelease); mixing them with /MD objects fails at
# link time (LNK2038 mismatch, LNK1169 multiply defined symbols).
#  - rustflags: Rust std and every cc/cmake-built -sys crate use /MT.
#  - LLAMA_STATIC_CRT: llama-cpp-sys-2 builds llama.cpp with /MT (it does not
#    follow crt-static on its own). Ignored on macOS and Linux.
# Side effect: the Windows app no longer needs the VC++ redistributable.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[env]
LLAMA_STATIC_CRT = "1"
