// Built-in finance / economics / accounting glossary, Chinese → Vietnamese
// (English kept for reference and future tri-lingual display).
//
// Loaded on demand from Settings › Engine dịch › "Nạp từ điển tài chính" and
// merged into the active course profile: `zh` goes to Soniox `terms`
// (transcription hints) and `{zh → vi}` to `translation_terms` (glossary).
// Keep entries as the canonical textbook forms a lecturer would say.

export const FINANCE_GLOSSARY = [
  // ── Financial statements & accounting ────────────────────────────────
  { zh: '资产负债表', en: 'balance sheet', vi: 'bảng cân đối kế toán' },
  { zh: '利润表', en: 'income statement', vi: 'báo cáo kết quả kinh doanh' },
  { zh: '损益表', en: 'profit and loss statement', vi: 'báo cáo lãi lỗ' },
  { zh: '现金流量表', en: 'cash flow statement', vi: 'báo cáo lưu chuyển tiền tệ' },
  { zh: '所有者权益变动表', en: 'statement of changes in equity', vi: 'báo cáo thay đổi vốn chủ sở hữu' },
  { zh: '财务报表', en: 'financial statements', vi: 'báo cáo tài chính' },
  { zh: '资产', en: 'assets', vi: 'tài sản' },
  { zh: '负债', en: 'liabilities', vi: 'nợ phải trả' },
  { zh: '所有者权益', en: "owners' equity", vi: 'vốn chủ sở hữu' },
  { zh: '股东权益', en: "shareholders' equity", vi: 'vốn chủ sở hữu (cổ đông)' },
  { zh: '流动资产', en: 'current assets', vi: 'tài sản ngắn hạn' },
  { zh: '非流动资产', en: 'non-current assets', vi: 'tài sản dài hạn' },
  { zh: '固定资产', en: 'fixed assets', vi: 'tài sản cố định' },
  { zh: '无形资产', en: 'intangible assets', vi: 'tài sản vô hình' },
  { zh: '商誉', en: 'goodwill', vi: 'lợi thế thương mại' },
  { zh: '流动负债', en: 'current liabilities', vi: 'nợ ngắn hạn' },
  { zh: '长期负债', en: 'long-term liabilities', vi: 'nợ dài hạn' },
  { zh: '应收账款', en: 'accounts receivable', vi: 'phải thu khách hàng' },
  { zh: '应付账款', en: 'accounts payable', vi: 'phải trả người bán' },
  { zh: '存货', en: 'inventory', vi: 'hàng tồn kho' },
  { zh: '折旧', en: 'depreciation', vi: 'khấu hao' },
  { zh: '摊销', en: 'amortization', vi: 'phân bổ (khấu hao tài sản vô hình)' },
  { zh: '减值', en: 'impairment', vi: 'suy giảm giá trị' },
  { zh: '营业收入', en: 'operating revenue', vi: 'doanh thu hoạt động' },
  { zh: '营业成本', en: 'cost of sales', vi: 'giá vốn hàng bán' },
  { zh: '毛利', en: 'gross profit', vi: 'lợi nhuận gộp' },
  { zh: '毛利率', en: 'gross margin', vi: 'biên lợi nhuận gộp' },
  { zh: '营业利润', en: 'operating profit', vi: 'lợi nhuận hoạt động' },
  { zh: '净利润', en: 'net income', vi: 'lợi nhuận ròng' },
  { zh: '息税前利润', en: 'EBIT', vi: 'lợi nhuận trước lãi vay và thuế (EBIT)' },
  { zh: '息税折旧摊销前利润', en: 'EBITDA', vi: 'EBITDA' },
  { zh: '每股收益', en: 'earnings per share', vi: 'lợi nhuận trên mỗi cổ phiếu (EPS)' },
  { zh: '留存收益', en: 'retained earnings', vi: 'lợi nhuận giữ lại' },
  { zh: '权责发生制', en: 'accrual basis', vi: 'cơ sở dồn tích' },
  { zh: '收付实现制', en: 'cash basis', vi: 'cơ sở tiền mặt' },
  { zh: '会计准则', en: 'accounting standards', vi: 'chuẩn mực kế toán' },
  { zh: '审计', en: 'audit', vi: 'kiểm toán' },
  { zh: '公允价值', en: 'fair value', vi: 'giá trị hợp lý' },
  { zh: '账面价值', en: 'book value', vi: 'giá trị sổ sách' },
  { zh: '经营活动现金流', en: 'operating cash flow', vi: 'dòng tiền từ hoạt động kinh doanh' },
  { zh: '投资活动现金流', en: 'investing cash flow', vi: 'dòng tiền từ hoạt động đầu tư' },
  { zh: '筹资活动现金流', en: 'financing cash flow', vi: 'dòng tiền từ hoạt động tài chính' },
  { zh: '自由现金流', en: 'free cash flow', vi: 'dòng tiền tự do' },

  // ── Financial ratios ──────────────────────────────────────────────────
  { zh: '流动比率', en: 'current ratio', vi: 'hệ số thanh toán hiện hành' },
  { zh: '速动比率', en: 'quick ratio', vi: 'hệ số thanh toán nhanh' },
  { zh: '资产负债率', en: 'debt-to-asset ratio', vi: 'hệ số nợ trên tài sản' },
  { zh: '产权比率', en: 'debt-to-equity ratio', vi: 'hệ số nợ trên vốn chủ sở hữu' },
  { zh: '利息保障倍数', en: 'interest coverage ratio', vi: 'hệ số khả năng trả lãi' },
  { zh: '净资产收益率', en: 'return on equity (ROE)', vi: 'tỷ suất sinh lời trên vốn chủ sở hữu (ROE)' },
  { zh: '总资产收益率', en: 'return on assets (ROA)', vi: 'tỷ suất sinh lời trên tổng tài sản (ROA)' },
  { zh: '投资回报率', en: 'return on investment (ROI)', vi: 'tỷ suất hoàn vốn đầu tư (ROI)' },
  { zh: '市盈率', en: 'price-to-earnings ratio (P/E)', vi: 'hệ số giá trên lợi nhuận (P/E)' },
  { zh: '市净率', en: 'price-to-book ratio (P/B)', vi: 'hệ số giá trên giá trị sổ sách (P/B)' },
  { zh: '存货周转率', en: 'inventory turnover', vi: 'vòng quay hàng tồn kho' },
  { zh: '应收账款周转率', en: 'receivables turnover', vi: 'vòng quay khoản phải thu' },
  { zh: '杜邦分析', en: 'DuPont analysis', vi: 'phân tích DuPont' },
  { zh: '财务杠杆', en: 'financial leverage', vi: 'đòn bẩy tài chính' },
  { zh: '经营杠杆', en: 'operating leverage', vi: 'đòn bẩy hoạt động' },

  // ── Corporate finance ─────────────────────────────────────────────────
  { zh: '公司金融', en: 'corporate finance', vi: 'tài chính doanh nghiệp' },
  { zh: '货币时间价值', en: 'time value of money', vi: 'giá trị thời gian của tiền' },
  { zh: '现值', en: 'present value', vi: 'giá trị hiện tại' },
  { zh: '终值', en: 'future value / terminal value', vi: 'giá trị tương lai (FV) / giá trị cuối kỳ (terminal value)' },
  { zh: '净现值', en: 'net present value (NPV)', vi: 'giá trị hiện tại ròng (NPV)' },
  { zh: '内部收益率', en: 'internal rate of return (IRR)', vi: 'tỷ suất hoàn vốn nội bộ (IRR)' },
  { zh: '回收期', en: 'payback period', vi: 'thời gian hoàn vốn' },
  { zh: '折现率', en: 'discount rate', vi: 'tỷ lệ chiết khấu' },
  { zh: '折现', en: 'discounting', vi: 'chiết khấu' },
  { zh: '年金', en: 'annuity', vi: 'dòng tiền đều (niên kim)' },
  { zh: '永续年金', en: 'perpetuity', vi: 'dòng tiền đều vĩnh viễn' },
  { zh: '复利', en: 'compound interest', vi: 'lãi kép' },
  { zh: '单利', en: 'simple interest', vi: 'lãi đơn' },
  { zh: '资本成本', en: 'cost of capital', vi: 'chi phí vốn' },
  { zh: '加权平均资本成本', en: 'WACC', vi: 'chi phí vốn bình quân gia quyền (WACC)' },
  { zh: '权益成本', en: 'cost of equity', vi: 'chi phí vốn chủ sở hữu' },
  { zh: '债务成本', en: 'cost of debt', vi: 'chi phí nợ vay' },
  { zh: '资本结构', en: 'capital structure', vi: 'cấu trúc vốn' },
  { zh: '资本预算', en: 'capital budgeting', vi: 'hoạch định ngân sách vốn' },
  { zh: '股利政策', en: 'dividend policy', vi: 'chính sách cổ tức' },
  { zh: '股利', en: 'dividend', vi: 'cổ tức' },
  { zh: '股票回购', en: 'share buyback', vi: 'mua lại cổ phiếu' },
  { zh: '首次公开发行', en: 'IPO', vi: 'phát hành cổ phiếu lần đầu ra công chúng (IPO)' },
  { zh: '并购', en: 'mergers and acquisitions', vi: 'mua bán và sáp nhập (M&A)' },
  { zh: '杠杆收购', en: 'leveraged buyout', vi: 'mua lại bằng đòn bẩy (LBO)' },
  { zh: '企业估值', en: 'valuation', vi: 'định giá doanh nghiệp' },
  { zh: '现金流折现', en: 'discounted cash flow (DCF)', vi: 'chiết khấu dòng tiền (DCF)' },
  { zh: '营运资本', en: 'working capital', vi: 'vốn lưu động' },
  { zh: '代理问题', en: 'agency problem', vi: 'vấn đề đại diện' },
  { zh: '信息不对称', en: 'information asymmetry', vi: 'bất cân xứng thông tin' },
  { zh: '道德风险', en: 'moral hazard', vi: 'rủi ro đạo đức' },
  { zh: '逆向选择', en: 'adverse selection', vi: 'lựa chọn ngược' },
  { zh: '优序融资理论', en: 'pecking order theory', vi: 'lý thuyết trật tự phân hạng' },
  { zh: 'MM定理', en: 'Modigliani–Miller theorem', vi: 'định lý Modigliani–Miller' },
  { zh: '税盾', en: 'tax shield', vi: 'lá chắn thuế' },
  { zh: '破产成本', en: 'bankruptcy cost', vi: 'chi phí phá sản' },

  // ── Investments & securities ──────────────────────────────────────────
  { zh: '投资学', en: 'investments', vi: 'đầu tư' },
  { zh: '证券', en: 'securities', vi: 'chứng khoán' },
  { zh: '股票', en: 'stock', vi: 'cổ phiếu' },
  { zh: '普通股', en: 'common stock', vi: 'cổ phiếu phổ thông' },
  { zh: '优先股', en: 'preferred stock', vi: 'cổ phiếu ưu đãi' },
  { zh: '债券', en: 'bond', vi: 'trái phiếu' },
  { zh: '国债', en: 'government bond', vi: 'trái phiếu chính phủ' },
  { zh: '公司债', en: 'corporate bond', vi: 'trái phiếu doanh nghiệp' },
  { zh: '可转换债券', en: 'convertible bond', vi: 'trái phiếu chuyển đổi' },
  { zh: '票面利率', en: 'coupon rate', vi: 'lãi suất coupon' },
  { zh: '到期收益率', en: 'yield to maturity', vi: 'lợi suất đáo hạn' },
  { zh: '久期', en: 'duration', vi: 'thời lượng (duration)' },
  { zh: '凸性', en: 'convexity', vi: 'độ lồi (convexity)' },
  { zh: '收益率曲线', en: 'yield curve', vi: 'đường cong lợi suất' },
  { zh: '期限结构', en: 'term structure', vi: 'cấu trúc kỳ hạn' },
  { zh: '信用评级', en: 'credit rating', vi: 'xếp hạng tín nhiệm' },
  { zh: '信用利差', en: 'credit spread', vi: 'chênh lệch tín dụng' },
  { zh: '投资组合', en: 'portfolio', vi: 'danh mục đầu tư' },
  { zh: '资产配置', en: 'asset allocation', vi: 'phân bổ tài sản' },
  { zh: '分散化', en: 'diversification', vi: 'đa dạng hoá' },
  { zh: '系统性风险', en: 'systematic risk', vi: 'rủi ro hệ thống' },
  { zh: '非系统性风险', en: 'unsystematic risk', vi: 'rủi ro phi hệ thống' },
  { zh: '贝塔系数', en: 'beta', vi: 'hệ số beta' },
  { zh: '阿尔法', en: 'alpha', vi: 'alpha (lợi nhuận vượt trội)' },
  { zh: '资本资产定价模型', en: 'CAPM', vi: 'mô hình định giá tài sản vốn (CAPM)' },
  { zh: '套利定价理论', en: 'arbitrage pricing theory', vi: 'lý thuyết định giá chênh lệch (APT)' },
  { zh: '有效市场假说', en: 'efficient market hypothesis', vi: 'giả thuyết thị trường hiệu quả' },
  { zh: '有效前沿', en: 'efficient frontier', vi: 'đường biên hiệu quả' },
  { zh: '夏普比率', en: 'Sharpe ratio', vi: 'hệ số Sharpe' },
  { zh: '无风险利率', en: 'risk-free rate', vi: 'lãi suất phi rủi ro' },
  { zh: '风险溢价', en: 'risk premium', vi: 'phần bù rủi ro' },
  { zh: '预期收益率', en: 'expected return', vi: 'tỷ suất sinh lời kỳ vọng' },
  { zh: '标准差', en: 'standard deviation', vi: 'độ lệch chuẩn' },
  { zh: '方差', en: 'variance', vi: 'phương sai' },
  { zh: '协方差', en: 'covariance', vi: 'hiệp phương sai' },
  { zh: '相关系数', en: 'correlation coefficient', vi: 'hệ số tương quan' },
  { zh: '波动率', en: 'volatility', vi: 'độ biến động' },
  { zh: '流动性', en: 'liquidity', vi: 'tính thanh khoản' },
  { zh: '做多', en: 'long position', vi: 'mua (vị thế mua)' },
  { zh: '做空', en: 'short selling', vi: 'bán khống' },
  { zh: '保证金', en: 'margin', vi: 'ký quỹ' },
  { zh: '杠杆', en: 'leverage', vi: 'đòn bẩy' },
  { zh: '套利', en: 'arbitrage', vi: 'kinh doanh chênh lệch giá' },
  { zh: '对冲', en: 'hedging', vi: 'phòng ngừa rủi ro (hedging)' },
  { zh: '投机', en: 'speculation', vi: 'đầu cơ' },
  { zh: '牛市', en: 'bull market', vi: 'thị trường giá lên' },
  { zh: '熊市', en: 'bear market', vi: 'thị trường giá xuống' },
  { zh: '市值', en: 'market capitalization', vi: 'vốn hoá thị trường' },
  { zh: '指数基金', en: 'index fund', vi: 'quỹ chỉ số' },
  { zh: '共同基金', en: 'mutual fund', vi: 'quỹ tương hỗ' },
  { zh: '交易所交易基金', en: 'ETF', vi: 'quỹ hoán đổi danh mục (ETF)' },
  { zh: '对冲基金', en: 'hedge fund', vi: 'quỹ phòng hộ' },
  { zh: '私募股权', en: 'private equity', vi: 'vốn cổ phần tư nhân' },
  { zh: '风险投资', en: 'venture capital', vi: 'đầu tư mạo hiểm' },
  { zh: '沪深300', en: 'CSI 300 index', vi: 'chỉ số CSI 300' },
  { zh: '上证指数', en: 'Shanghai Composite Index', vi: 'chỉ số tổng hợp Thượng Hải' },
  { zh: 'A股', en: 'A-shares', vi: 'cổ phiếu hạng A' },
  { zh: '港股', en: 'Hong Kong stocks', vi: 'cổ phiếu Hồng Kông' },

  // ── Derivatives ───────────────────────────────────────────────────────
  { zh: '衍生品', en: 'derivatives', vi: 'công cụ phái sinh' },
  { zh: '金融衍生工具', en: 'financial derivatives', vi: 'công cụ tài chính phái sinh' },
  { zh: '期货', en: 'futures', vi: 'hợp đồng tương lai' },
  { zh: '远期合约', en: 'forward contract', vi: 'hợp đồng kỳ hạn' },
  { zh: '期权', en: 'option', vi: 'quyền chọn' },
  { zh: '看涨期权', en: 'call option', vi: 'quyền chọn mua' },
  { zh: '看跌期权', en: 'put option', vi: 'quyền chọn bán' },
  { zh: '行权价', en: 'strike price', vi: 'giá thực hiện' },
  { zh: '到期日', en: 'expiration date', vi: 'ngày đáo hạn' },
  { zh: '互换', en: 'swap', vi: 'hợp đồng hoán đổi' },
  { zh: '利率互换', en: 'interest rate swap', vi: 'hoán đổi lãi suất' },
  { zh: '信用违约互换', en: 'credit default swap', vi: 'hoán đổi rủi ro tín dụng (CDS)' },
  { zh: '布莱克-斯科尔斯模型', en: 'Black–Scholes model', vi: 'mô hình Black–Scholes' },
  { zh: '标的资产', en: 'underlying asset', vi: 'tài sản cơ sở' },
  { zh: '内在价值', en: 'intrinsic value', vi: 'giá trị nội tại' },
  { zh: '时间价值', en: 'time value', vi: 'giá trị thời gian' },
  { zh: '隐含波动率', en: 'implied volatility', vi: 'độ biến động hàm ý' },

  // ── Banking, money & monetary policy ──────────────────────────────────
  { zh: '货币银行学', en: 'money and banking', vi: 'tiền tệ và ngân hàng' },
  { zh: '中央银行', en: 'central bank', vi: 'ngân hàng trung ương' },
  { zh: '中国人民银行', en: "People's Bank of China", vi: 'Ngân hàng Nhân dân Trung Quốc' },
  { zh: '美联储', en: 'Federal Reserve', vi: 'Cục Dự trữ Liên bang Mỹ (Fed)' },
  { zh: '商业银行', en: 'commercial bank', vi: 'ngân hàng thương mại' },
  { zh: '投资银行', en: 'investment bank', vi: 'ngân hàng đầu tư' },
  { zh: '货币政策', en: 'monetary policy', vi: 'chính sách tiền tệ' },
  { zh: '财政政策', en: 'fiscal policy', vi: 'chính sách tài khoá' },
  { zh: '量化宽松', en: 'quantitative easing', vi: 'nới lỏng định lượng (QE)' },
  { zh: '基准利率', en: 'benchmark interest rate', vi: 'lãi suất cơ bản' },
  { zh: '存款准备金率', en: 'reserve requirement ratio', vi: 'tỷ lệ dự trữ bắt buộc' },
  { zh: '公开市场操作', en: 'open market operations', vi: 'nghiệp vụ thị trường mở' },
  { zh: '贷款市场报价利率', en: 'loan prime rate (LPR)', vi: 'lãi suất cho vay cơ bản (LPR)' },
  { zh: '货币供应量', en: 'money supply', vi: 'cung tiền' },
  { zh: '货币乘数', en: 'money multiplier', vi: 'số nhân tiền' },
  { zh: '通货膨胀', en: 'inflation', vi: 'lạm phát' },
  { zh: '通货紧缩', en: 'deflation', vi: 'giảm phát' },
  { zh: '汇率', en: 'exchange rate', vi: 'tỷ giá hối đoái' },
  { zh: '人民币', en: 'renminbi', vi: 'nhân dân tệ' },
  { zh: '外汇储备', en: 'foreign exchange reserves', vi: 'dự trữ ngoại hối' },
  { zh: '资本管制', en: 'capital controls', vi: 'kiểm soát vốn' },
  { zh: '信贷', en: 'credit', vi: 'tín dụng' },
  { zh: '不良贷款', en: 'non-performing loan', vi: 'nợ xấu' },
  { zh: '资本充足率', en: 'capital adequacy ratio', vi: 'tỷ lệ an toàn vốn' },
  { zh: '巴塞尔协议', en: 'Basel Accords', vi: 'Hiệp ước Basel' },
  { zh: '影子银行', en: 'shadow banking', vi: 'ngân hàng ngầm' },
  { zh: '金融监管', en: 'financial regulation', vi: 'giám sát tài chính' },
  { zh: '系统性金融风险', en: 'systemic financial risk', vi: 'rủi ro tài chính hệ thống' },
  { zh: '金融科技', en: 'fintech', vi: 'công nghệ tài chính' },
  { zh: '数字人民币', en: 'digital yuan (e-CNY)', vi: 'nhân dân tệ kỹ thuật số' },
  { zh: '资产证券化', en: 'securitization', vi: 'chứng khoán hoá tài sản' },
  { zh: '抵押贷款', en: 'mortgage', vi: 'vay thế chấp' },

  // ── Macroeconomics ────────────────────────────────────────────────────
  { zh: '宏观经济学', en: 'macroeconomics', vi: 'kinh tế vĩ mô' },
  { zh: '微观经济学', en: 'microeconomics', vi: 'kinh tế vi mô' },
  { zh: '国内生产总值', en: 'GDP', vi: 'tổng sản phẩm quốc nội (GDP)' },
  { zh: '经济增长', en: 'economic growth', vi: 'tăng trưởng kinh tế' },
  { zh: '经济周期', en: 'business cycle', vi: 'chu kỳ kinh tế' },
  { zh: '衰退', en: 'recession', vi: 'suy thoái' },
  { zh: '失业率', en: 'unemployment rate', vi: 'tỷ lệ thất nghiệp' },
  { zh: '消费者价格指数', en: 'consumer price index (CPI)', vi: 'chỉ số giá tiêu dùng (CPI)' },
  { zh: '总需求', en: 'aggregate demand', vi: 'tổng cầu' },
  { zh: '总供给', en: 'aggregate supply', vi: 'tổng cung' },
  { zh: '供求关系', en: 'supply and demand', vi: 'quan hệ cung cầu' },
  { zh: '均衡', en: 'equilibrium', vi: 'cân bằng' },
  { zh: '弹性', en: 'elasticity', vi: 'độ co giãn' },
  { zh: '边际', en: 'marginal', vi: 'biên' },
  { zh: '边际效用', en: 'marginal utility', vi: 'hữu dụng biên' },
  { zh: '机会成本', en: 'opportunity cost', vi: 'chi phí cơ hội' },
  { zh: '外部性', en: 'externality', vi: 'ngoại ứng' },
  { zh: '公共物品', en: 'public goods', vi: 'hàng hoá công' },
  { zh: '市场失灵', en: 'market failure', vi: 'thất bại thị trường' },
  { zh: '贸易顺差', en: 'trade surplus', vi: 'thặng dư thương mại' },
  { zh: '贸易逆差', en: 'trade deficit', vi: 'thâm hụt thương mại' },
  { zh: '国际收支', en: 'balance of payments', vi: 'cán cân thanh toán' },
  { zh: '经常账户', en: 'current account', vi: 'tài khoản vãng lai' },
  { zh: '资本账户', en: 'capital account', vi: 'tài khoản vốn' },
  { zh: '一带一路', en: 'Belt and Road Initiative', vi: 'sáng kiến Vành đai và Con đường' },

  // ── Econometrics & quantitative methods ───────────────────────────────
  { zh: '计量经济学', en: 'econometrics', vi: 'kinh tế lượng' },
  { zh: '回归分析', en: 'regression analysis', vi: 'phân tích hồi quy' },
  { zh: '最小二乘法', en: 'ordinary least squares', vi: 'bình phương nhỏ nhất (OLS)' },
  { zh: '自变量', en: 'independent variable', vi: 'biến độc lập' },
  { zh: '因变量', en: 'dependent variable', vi: 'biến phụ thuộc' },
  { zh: '显著性', en: 'significance', vi: 'mức ý nghĩa' },
  { zh: '假设检验', en: 'hypothesis testing', vi: 'kiểm định giả thuyết' },
  { zh: '置信区间', en: 'confidence interval', vi: 'khoảng tin cậy' },
  { zh: '时间序列', en: 'time series', vi: 'chuỗi thời gian' },
  { zh: '面板数据', en: 'panel data', vi: 'dữ liệu bảng' },
  { zh: '内生性', en: 'endogeneity', vi: 'nội sinh' },
  { zh: '异方差', en: 'heteroskedasticity', vi: 'phương sai thay đổi' },
  { zh: '多重共线性', en: 'multicollinearity', vi: 'đa cộng tuyến' },
  { zh: '正态分布', en: 'normal distribution', vi: 'phân phối chuẩn' },
  { zh: '蒙特卡洛模拟', en: 'Monte Carlo simulation', vi: 'mô phỏng Monte Carlo' },
  { zh: '在险价值', en: 'value at risk (VaR)', vi: 'giá trị chịu rủi ro (VaR)' },
  { zh: '压力测试', en: 'stress test', vi: 'kiểm tra sức chịu đựng' },
  { zh: '风险管理', en: 'risk management', vi: 'quản trị rủi ro' },
  { zh: '信用风险', en: 'credit risk', vi: 'rủi ro tín dụng' },
  { zh: '市场风险', en: 'market risk', vi: 'rủi ro thị trường' },
  { zh: '操作风险', en: 'operational risk', vi: 'rủi ro hoạt động' },
  { zh: '流动性风险', en: 'liquidity risk', vi: 'rủi ro thanh khoản' },

  // ── Tax, law & governance ─────────────────────────────────────────────
  { zh: '企业所得税', en: 'corporate income tax', vi: 'thuế thu nhập doanh nghiệp' },
  { zh: '增值税', en: 'value-added tax', vi: 'thuế giá trị gia tăng' },
  { zh: '个人所得税', en: 'personal income tax', vi: 'thuế thu nhập cá nhân' },
  { zh: '公司治理', en: 'corporate governance', vi: 'quản trị công ty' },
  { zh: '董事会', en: 'board of directors', vi: 'hội đồng quản trị' },
  { zh: '股东大会', en: "shareholders' meeting", vi: 'đại hội cổ đông' },
  { zh: '内幕交易', en: 'insider trading', vi: 'giao dịch nội gián' },
  { zh: '证监会', en: 'securities regulatory commission', vi: 'Uỷ ban Chứng khoán (CSRC)' },
  { zh: '上市公司', en: 'listed company', vi: 'công ty niêm yết' },
  { zh: '有限责任公司', en: 'limited liability company', vi: 'công ty trách nhiệm hữu hạn' },
  { zh: '股份有限公司', en: 'joint-stock company', vi: 'công ty cổ phần' },
  { zh: '国有企业', en: 'state-owned enterprise', vi: 'doanh nghiệp nhà nước' },
  { zh: '民营企业', en: 'private enterprise', vi: 'doanh nghiệp tư nhân' },
  { zh: '中小企业', en: 'SMEs', vi: 'doanh nghiệp vừa và nhỏ' },
  { zh: 'ESG', en: 'ESG', vi: 'ESG (môi trường – xã hội – quản trị)' },
  { zh: '绿色金融', en: 'green finance', vi: 'tài chính xanh' },

  // ── Classroom phrases the lecturer uses ───────────────────────────────
  { zh: '这个考试会考', en: 'this will be on the exam', vi: 'phần này sẽ thi' },
  { zh: '重点', en: 'key point', vi: 'trọng tâm' },
  { zh: '难点', en: 'difficult point', vi: 'điểm khó' },
  { zh: '作业', en: 'homework', vi: 'bài tập về nhà' },
  { zh: '期中考试', en: 'midterm exam', vi: 'thi giữa kỳ' },
  { zh: '期末考试', en: 'final exam', vi: 'thi cuối kỳ' },
  { zh: '案例分析', en: 'case study', vi: 'phân tích tình huống' },
  { zh: '公式', en: 'formula', vi: 'công thức' },
  { zh: '假设', en: 'assumption', vi: 'giả định' },
  { zh: '推导', en: 'derivation', vi: 'suy diễn (chứng minh công thức)' },
  { zh: '课件', en: 'lecture slides', vi: 'slide bài giảng' },
  { zh: '教材', en: 'textbook', vi: 'giáo trình' },
  { zh: '论文', en: 'paper / thesis', vi: 'luận văn / bài báo khoa học' },
  { zh: '文献综述', en: 'literature review', vi: 'tổng quan tài liệu' },
];
